@baseURL=http://localhost:8000

@urlPath=api/v1/follow

### get following users endpoint
GET {{baseURL}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials:true


### get followers users endpoint
GET {{baseURL}}/{{urlPath}}/user/followers/64588902a8d043efedff0ee2
Content-Type: application/json
Accept: application/json
withCredentials:true

### follow
PUT {{baseURL}}/{{urlPath}}/user/64588902a8d043efedff0ee2
Content-Type: application/json
Accept: application/json
withCredentials:true

### unfollow
PUT {{baseURL}}/{{urlPath}}/user/unfollow/645888f6a8d043efedff0edb/645888e9a8d043efedff0ed4
Content-Type: application/json
Accept: application/json
withCredentials:true


