@baseURL=http://localhost:8000

@urlPath=api/v1/notification


### read notification endpoint
PUT {{baseURL}}/{{urlPath}}/6461b2a86f08a4b7a5269581
Content-Type: application/json
Accept: application/json
withCredentials:true


### delete notification endpoint
DELETE {{baseURL}}/{{urlPath}}/646122b56f08a4b7a5269576

Content-Type: application/json
Accept: application/json
withCredentials:true


